# Generated by Django 5.1.1 on 2024-10-01 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('type', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Ivoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(null=True)),
                ('Product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.product')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.user')),
            ],
        ),
    ]
