# Generated by Django 5.1.1 on 2024-10-01 04:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0002_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product_fk',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Ivoice',
        ),
    ]
