# Generated by Django 5.1.1 on 2024-10-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0006_alter_invoice_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pswd',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
